/**
 * Rules
 */
export const LIST_RULES = 'LIST_RULES';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_LOADED_STATUS = 'SET_LOADED_STATUS';
export const SET_LOADED_ERROR = 'SET_LOADED_ERROR';
export const GET_RULE = 'GET_RULE';
export const CREATE_RULE = 'CREATE_RULE';
export const UPDATE_RULE = 'UPDATE_RULE';
export const REMOVE_RULE = 'REMOVE_RULE';


/**
 * Auth
 */
export const SET_AUTH_INSTALL_URL = 'SET_AUTH_INSTALL_URL';
export const SET_AUTH_INSTALL_ERROR = 'SET_AUTH_INSTALL_ERROR';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTH_CURRENT_SHOP = 'SET_AUTH_CURRENT_SHOP';
export const SET_AUTH_DATA = 'SET_AUTH_DATA';
